# Generated by Django 5.2.4 on 2025-07-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='doctor',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
